export const REQUEST_CREATE_BLOG = "REQUEST_CREATE_BLOG"
export const SUCCESS_CREATE_BLOG = "SUCCESS_CREATE_BLOG"
export const FAIL_CREATE_BLOG = "FAIL_CREATE_BLOG"

export const REQUEST_DELETE_BLOG = "REQUEST_DELETE_BLOG"
export const SUCCESS_DELETE_BLOG = "SUCCESS_DELETE_BLOG"
export const FAIL_DELETE_BLOG = "FAIL_DELETE_BLOG"

export const REQUEST_GET_ALL_BLOGS = "REQUEST_GET_ALL_BLOGS"
export const SUCCESS_GET_ALL_BLOGS = "SUCCESS_GET_ALL_BLOGS"
export const FAIL_GET_ALL_BLOGS = "FAIL_GET_ALL_BLOGS"

export const REQUEST_GET_SPECIFIC_BLOG = "REQUEST_GET_SPECIFIC_BLOG"
export const SUCCESS_GET_SPECIFIC_BLOG = "SUCCESS_GET_SPECIFIC_BLOG"
export const FAIL_GET_SPECIFIC_BLOG = "FAIL_GET_SPECIFIC_BLOG"

export const REQUEST_BLOG_RESET = "REQUEST_BLOG_RESET"