export const REQUEST_USER_LOGIN = "REQUEST_USER_LOGIN"
export const SUCCESS_USER_LOGIN = "SUCCESS_USER_LOGIN"
export const FAIL_USER_LOGIN = "FAIL_USER_LOGIN"

export const REQUEST_USER_LOAD = "REQUEST_USER_LOAD"
export const SUCCESS_USER_LOAD = "SUCCESS_USER_LOAD"
export const FAIL_USER_LOAD = "FAIL_USER_LOAD"

export const REQUEST_USER_LOGOUT = "REQUEST_USER_LOGOUT"
export const SUCCESS_USER_LOGOUT = "SUCCESS_USER_LOGOUT"
export const FAIL_USER_LOGOUT = "FAIL_USER_LOGOUT"


export const REQUEST_USER_RESET = "REQUEST_USER_RESET"
